version: '3'
services:
  server-dev:
    build: ./server
    command: npm run dev
    ports:
      - "5000:80"
    volumes:
      - ./server:/usr/src/app
  server:
    build: ./server
    ports:
      - "4000:80"
    volumes:
      - ./server:/usr/src/app
  json-server:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 80 -w db.json
    volumes:
      - ./data:/data
    restart: always
  redis:
    image: "redis"