apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jsonplaceholder
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: jsonplaceholder
    spec:
      containers:
      - image: armedi/jsonplaceholder
        name: jsonplaceholder
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: jsonplaceholder
spec:
  ports:
  - port: 80
  selector:
    io.kompose.service: jsonplaceholder
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: redis
    spec:
      containers:
      - image: redis
        name: redis
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - port: 6379
  selector:
    io.kompose.service: redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: server
    spec:
      containers:
      - env:
        - name: JSONPLACEHOLDER
          value: http://jsonplaceholder
        - name: REDIS_HOST
          value: redis
        image: armedi/loyal-fox-graphql
        name: server
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    io.kompose.service: server